PKGBUILD/steamfork-device-support/src/etc/lib/steamfork_hwsupport/him_devicequirks/AYANEO-NEXT-Advance/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/etc/lib/steamfork_hwsupport/him_devicequirks/AYANEO-NEXT/hardware_quirks.sh
Change desktop rotation to right for both the Next and Next Advance
=> Update Ayaneo Next quirks

PKGBUILD/steamfork-device-support/src/etc/lib/steamfork_hwsupport/devicequirks/Anbernic-Win600/hardware_quirks.sh
No more apparent issues with audio watchdog since the latest updates, so I'm reenabling it.
=> Update Win600 quirks

PKGBUILD/linux/0060-asus-patch-series.patch, PKGBUILD/linux/PKGBUILD
Test s2idle DSM screen on/off changes by Antheas.
Drops all earlier s2idle change and CSEE quirk rubbish.
=> Update asus patches

PKGBUILD/linux/0060-asus-patch-series.patch
=> kernel: rebase asus patch series on 6.11.3

PKGBUILD/linux/0060-asus-patch-series.patch, PKGBUILD/linux/PKGBUILD
=> Update asus patch series

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/etc/gamescope/scripts/displays/AYA-AYANEOFHD.lua
- Modification to only support 61hz and 120hz - net savings of 4w in some cases.
=> Add @uejji's Ayaneo Flip KB panel configuration

Makefile, scripts/sync
Add a simple release process that merges down from the upstream project, checks the package repository against git, and then creates and pushes a tag to start the release workflow.
=> Add: make release

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/ayn-Loki-MiniPro/hardware_quirks.sh
Thanks to kaptainonline and sugoi_boii on Discord
=> Add quirk for AYN Loki Mini Pro

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/etc/gamescope/scripts/displays/CSW-PN8007QB1-1.lua
Original: https://github.com/ublue-os/bazzite/blob/main/spec_files/gamescope/handheld.patch#L2507
=> Add CSW-PN8007QB1-1 (Legion Go S), thanks to Bazzite.

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AOKZOE-AOKZOE-A1-AR07/hardware_quirks.sh
Thanks to markymark89_04 on Discord
=> Add quirks file for AOKZOE A1

PKGBUILD/linux/0060-asus-patch-series.patch, PKGBUILD/linux/PKGBUILD
Tested, some fixes made. Should result in an overall better experience.
=> asus: update kernel patch series

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/lib/udev/rules.d/71-oxp-turbo-takeover.rules
=> Add udev rule for OXP/AOKZOE turbo takeover

PKGBUILD/inputplumber/PKGBUILD, PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/etc/X11/xinit/xinitrc.d/060-digitizer-rotation.sh, PKGBUILD/steamfork-device-support/src/usr/bin/steamfork-quirk-generator, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-FLIP-KB/hardware_quirks.sh
* InputPlumber 0.44.1
* Switch ROTATE_DIGITIZER to an array, and add support for configuring multiple digitizers with differing rotation requirements (Flip DS).  Thanks to @pastaq for the idea!  See commit for syntax.
=> Update InputPlumber, improve digitizer rotation.

PKGBUILD/linux/0060-asus-patch-series.patch, PKGBUILD/linux/PKGBUILD
Notable changes:
- MCU powersave is set to on if FW is correct version
- Old CSEE hacks are disabled if MCU FW is correct version
- MCU FW warning in log if MCU FW is lower than reqiurements
=> kernel: asus: update patch series

.github/workflows/build_all_packages.yml, .github/workflows/build_and_sync.yml
This reverts commit 5b235eaf284cba029f4ee23e75657cbfc0d68f1f.
=> Revert "Workflow optimizations."

.github/workflows/build_all_packages.yml, .github/workflows/build_and_sync.yml, PKGBUILD/gamescope/PKGBUILD, PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/bin/steamfork-audio-watchdog, PKGBUILD/xorg-xwayland/PKGBUILD, scripts/build_package
* xorg-xwayland 24.1.6
* Workflow optimizations (still disabled by default).
* Add support for disabling specific audio routes. using the audio.routing property.
=> xorg-wayland bump, audio routing property, workflow optimization (still WIP).

PKGBUILD/linux/0001-drm-panel-orientation-quirks.patch, PKGBUILD/linux/9000-upstreamed-drm-panel-orientation-quirks.patch, PKGBUILD/linux/PKGBUILD
-Moved upstreamed patches into a separate file to be easily removed later
-Added support for more AYANEO 2021 devices
=> Update panel orientation quirks patch

PKGBUILD/linux/0001-drm-panel-orientation-quirks.patch, PKGBUILD/linux/PKGBUILD, PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2021-Pro-Retro-Power/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/ONE-NETBOOK-ONEXPLAYER-F1Pro/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/Tectoy-Zeenix-Lite
Draft until I write and include the panel orientation quirk patch
=> Add devices support

PKGBUILD/linux/PKGBUILD
=> Update patch shasum

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/etc/gamescope/scripts/displays/YHB-YHB02P25.lua, PKGBUILD/steamfork-device-support/src/etc/inputplumber/devices.d/50-onexplayer_onexfly_pro.yaml, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/ONE-NETBOOK-ONEXPLAYER-F1Pro/hardware_quirks.sh
HDR values from https://github.com/ublue-os/bazzite/issues/2369#issuecomment-2720224477
InputPlumber YAML is temporary until we merge official support
=> Update support for OneXFly F1 Pro

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-KUN/hardware_quirks.sh
=> Add quirk for Ayaneo Kun

PKGBUILD/steamfork-device-support/PKGBUILD, PKGBUILD/steamfork-device-support/src/etc/gamescope/scripts/displays/HSX-YHB03P24.lua, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYA-NEO-AYA-NEO-Founder/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AIR-1S/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AIR/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2021-Pro-Retro-Power/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2021-Pro/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2021/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-2S/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-AYANEO-NEXT-Pro/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-FLIP-DS/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-FLIP-KB/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-NEXT-Advance/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-NEXT/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/AYANEO-SLIDE/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/GPD-G1628-04/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/LENOVO-83E1/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/Micro-Computer-HK-Tech-Limited-UM580-Series/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/ONE-NETBOOK-TECHNOLOGY-CO-LTD-ONE-XPLAYER/hardware_quirks.sh, PKGBUILD/steamfork-device-support/src/usr/lib/hwsupport/devicequirks/ayn-Loki-MiniPro/hardware_quirks.sh
Cleanup quirks files and add quirks for GPD Pocket 4
=> steamfork-device-support 202504.12-1
